apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-stalux
spec:
  displayName: Stalux
  author:
    name: 晨阳
    website: https://www.puresky.top
  description: A starter theme for Halo.
  logo: https://www.halo.run/logo
  homepage: https://github.com/imorisun/halo-theme-stalux
  repo: https://github.com/imorisun/halo-theme-stalux.git
  issues: https://github.com/imorisun/halo-theme-stalux/issues
  version: "1.0.0"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
